[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "sfp-nsdsyn"
version = "0.1.0"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["sfp_nsdsyn*"]
